[build]
  base = "crypto-react-app"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://web-coinmarketcapapikey.up.railway.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://web-coinmarketcapapikey.up.railway.app/api"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://web-coinmarketcapapikey.up.railway.app/api" 